---
abstract: 'Find and use installed modules in a (sub)category'
author:
  - 'Christian Renz <crenz@web42.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Find
no_index:
  directory:
    - t
    - inc
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  File::Find: 0
  File::Spec: 0
  perl: 5.006001
resources:
  repository: http://github.com/crenz/Module-Find
version: 0.10_01
